In [2]:
import pandas as pd

books = pd.read_csv("categoriesed_books.csv")

In [4]:
from transformers import pipeline

classifier = pipeline(
    "text-classification",
    model="j-hartmann/emotion-english-distilroberta-base",
    top_k=None,
    device=-1  # CPU
)

Device set to use cpu

In [5]:
books["description"][0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.'

In [6]:
classifier(books["description"][0])

C:\Users\23156\PycharmProjects\Book-recommendation-system\.venv\Lib\site-packages\torch\nn\modules\module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `RobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

[[{'label': 'fear', 'score': 0.6548399925231934},
  {'label': 'neutral', 'score': 0.1698525995016098},
  {'label': 'sadness', 'score': 0.11640939861536026},
  {'label': 'surprise', 'score': 0.02070068009197712},
  {'label': 'disgust', 'score': 0.019100721925497055},
  {'label': 'joy', 'score': 0.015161462128162384},
  {'label': 'anger', 'score': 0.003935154061764479}]]

In [7]:
classifier(books["description"][0].split("."))

[[{'label': 'surprise', 'score': 0.729602038860321},
  {'label': 'neutral', 'score': 0.14038607478141785},
  {'label': 'fear', 'score': 0.06816229224205017},
  {'label': 'joy', 'score': 0.04794258251786232},
  {'label': 'anger', 'score': 0.009156374260783195},
  {'label': 'disgust', 'score': 0.002628477755934},
  {'label': 'sadness', 'score': 0.0021221644710749388}],
 [{'label': 'neutral', 'score': 0.44937077164649963},
  {'label': 'disgust', 'score': 0.27359139919281006},
  {'label': 'joy', 'score': 0.10908306390047073},
  {'label': 'sadness', 'score': 0.09362738579511642},
  {'label': 'anger', 'score': 0.040478240698575974},
  {'label': 'surprise', 'score': 0.02697017788887024},
  {'label': 'fear', 'score': 0.0068790484219789505}],
 [{'label': 'neutral', 'score': 0.6462157964706421},
  {'label': 'sadness', 'score': 0.24273352324962616},
  {'label': 'disgust', 'score': 0.04342266544699669},
  {'label': 'surprise', 'score': 0.028300534933805466},
  {'label': 'joy', 'score': 0.014211485162377357},
  {'label': 'fear', 'score': 0.014084087684750557},
  {'label': 'anger', 'score': 0.011031894013285637}],
 [{'label': 'fear', 'score': 0.9281681180000305},
  {'label': 'anger', 'score': 0.03219093754887581},
  {'label': 'neutral', 'score': 0.01280868798494339},
  {'label': 'sadness', 'score': 0.008756876923143864},
  {'label': 'surprise', 'score': 0.008597906678915024},
  {'label': 'disgust', 'score': 0.008431830443441868},
  {'label': 'joy', 'score': 0.0010455821175128222}],
 [{'label': 'sadness', 'score': 0.9671575427055359},
  {'label': 'neutral', 'score': 0.015104157850146294},
  {'label': 'disgust', 'score': 0.006480599287897348},
  {'label': 'fear', 'score': 0.005393992643803358},
  {'label': 'surprise', 'score': 0.0022869419772177935},
  {'label': 'anger', 'score': 0.0018428912153467536},
  {'label': 'joy', 'score': 0.0017338789766654372}],
 [{'label': 'joy', 'score': 0.9327982664108276},
  {'label': 'disgust', 'score': 0.03771700710058212},
  {'label': 'neutral', 'score': 0.015891820192337036},
  {'label': 'sadness', 'score': 0.006444503553211689},
  {'label': 'anger', 'score': 0.005024963989853859},
  {'label': 'surprise', 'score': 0.0015812061028555036},
  {'label': 'fear', 'score': 0.0005423057591542602}],
 [{'label': 'joy', 'score': 0.6528709530830383},
  {'label': 'neutral', 'score': 0.25427451729774475},
  {'label': 'surprise', 'score': 0.06808296591043472},
  {'label': 'sadness', 'score': 0.009908993728458881},
  {'label': 'disgust', 'score': 0.006512218154966831},
  {'label': 'anger', 'score': 0.004821305628865957},
  {'label': 'fear', 'score': 0.0035290149971842766}],
 [{'label': 'neutral', 'score': 0.5494772791862488},
  {'label': 'sadness', 'score': 0.11169009655714035},
  {'label': 'disgust', 'score': 0.10400658845901489},
  {'label': 'surprise', 'score': 0.07876544445753098},
  {'label': 'anger', 'score': 0.06413355469703674},
  {'label': 'fear', 'score': 0.05136274918913841},
  {'label': 'joy', 'score': 0.040564365684986115}]]

In [8]:
sentences = books["description"][0].split(".")
predictions = classifier(sentences)

In [9]:
predictions[0]

[{'label': 'surprise', 'score': 0.729602038860321},
 {'label': 'neutral', 'score': 0.14038607478141785},
 {'label': 'fear', 'score': 0.06816229224205017},
 {'label': 'joy', 'score': 0.04794258251786232},
 {'label': 'anger', 'score': 0.009156374260783195},
 {'label': 'disgust', 'score': 0.002628477755934},
 {'label': 'sadness', 'score': 0.0021221644710749388}]

In [10]:
sentences[3]

' Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist'

In [11]:
predictions[3]

[{'label': 'fear', 'score': 0.9281681180000305},
 {'label': 'anger', 'score': 0.03219093754887581},
 {'label': 'neutral', 'score': 0.01280868798494339},
 {'label': 'sadness', 'score': 0.008756876923143864},
 {'label': 'surprise', 'score': 0.008597906678915024},
 {'label': 'disgust', 'score': 0.008431830443441868},
 {'label': 'joy', 'score': 0.0010455821175128222}]

In [12]:
predictions

[[{'label': 'surprise', 'score': 0.729602038860321},
  {'label': 'neutral', 'score': 0.14038607478141785},
  {'label': 'fear', 'score': 0.06816229224205017},
  {'label': 'joy', 'score': 0.04794258251786232},
  {'label': 'anger', 'score': 0.009156374260783195},
  {'label': 'disgust', 'score': 0.002628477755934},
  {'label': 'sadness', 'score': 0.0021221644710749388}],
 [{'label': 'neutral', 'score': 0.44937077164649963},
  {'label': 'disgust', 'score': 0.27359139919281006},
  {'label': 'joy', 'score': 0.10908306390047073},
  {'label': 'sadness', 'score': 0.09362738579511642},
  {'label': 'anger', 'score': 0.040478240698575974},
  {'label': 'surprise', 'score': 0.02697017788887024},
  {'label': 'fear', 'score': 0.0068790484219789505}],
 [{'label': 'neutral', 'score': 0.6462157964706421},
  {'label': 'sadness', 'score': 0.24273352324962616},
  {'label': 'disgust', 'score': 0.04342266544699669},
  {'label': 'surprise', 'score': 0.028300534933805466},
  {'label': 'joy', 'score': 0.014211485162377357},
  {'label': 'fear', 'score': 0.014084087684750557},
  {'label': 'anger', 'score': 0.011031894013285637}],
 [{'label': 'fear', 'score': 0.9281681180000305},
  {'label': 'anger', 'score': 0.03219093754887581},
  {'label': 'neutral', 'score': 0.01280868798494339},
  {'label': 'sadness', 'score': 0.008756876923143864},
  {'label': 'surprise', 'score': 0.008597906678915024},
  {'label': 'disgust', 'score': 0.008431830443441868},
  {'label': 'joy', 'score': 0.0010455821175128222}],
 [{'label': 'sadness', 'score': 0.9671575427055359},
  {'label': 'neutral', 'score': 0.015104157850146294},
  {'label': 'disgust', 'score': 0.006480599287897348},
  {'label': 'fear', 'score': 0.005393992643803358},
  {'label': 'surprise', 'score': 0.0022869419772177935},
  {'label': 'anger', 'score': 0.0018428912153467536},
  {'label': 'joy', 'score': 0.0017338789766654372}],
 [{'label': 'joy', 'score': 0.9327982664108276},
  {'label': 'disgust', 'score': 0.03771700710058212},
  {'label': 'neutral', 'score': 0.015891820192337036},
  {'label': 'sadness', 'score': 0.006444503553211689},
  {'label': 'anger', 'score': 0.005024963989853859},
  {'label': 'surprise', 'score': 0.0015812061028555036},
  {'label': 'fear', 'score': 0.0005423057591542602}],
 [{'label': 'joy', 'score': 0.6528709530830383},
  {'label': 'neutral', 'score': 0.25427451729774475},
  {'label': 'surprise', 'score': 0.06808296591043472},
  {'label': 'sadness', 'score': 0.009908993728458881},
  {'label': 'disgust', 'score': 0.006512218154966831},
  {'label': 'anger', 'score': 0.004821305628865957},
  {'label': 'fear', 'score': 0.0035290149971842766}],
 [{'label': 'neutral', 'score': 0.5494772791862488},
  {'label': 'sadness', 'score': 0.11169009655714035},
  {'label': 'disgust', 'score': 0.10400658845901489},
  {'label': 'surprise', 'score': 0.07876544445753098},
  {'label': 'anger', 'score': 0.06413355469703674},
  {'label': 'fear', 'score': 0.05136274918913841},
  {'label': 'joy', 'score': 0.040564365684986115}]]

In [13]:
sorted(predictions[0], key=lambda x: x["label"])

[{'label': 'anger', 'score': 0.009156374260783195},
 {'label': 'disgust', 'score': 0.002628477755934},
 {'label': 'fear', 'score': 0.06816229224205017},
 {'label': 'joy', 'score': 0.04794258251786232},
 {'label': 'neutral', 'score': 0.14038607478141785},
 {'label': 'sadness', 'score': 0.0021221644710749388},
 {'label': 'surprise', 'score': 0.729602038860321}]

In [14]:
import numpy as np

emotion_labels = ["anger", "disgust", "fear", "joy", "sadness", "surprise", "neutral"]
isbn = []
emotion_scores = {label: [] for label in emotion_labels}

def calculate_max_emotion_scores(predictions):
    per_emotion_scores = {label: [] for label in emotion_labels}
    for prediction in predictions:
        sorted_predictions = sorted(prediction, key=lambda x: x["label"])
        for index, label in enumerate(emotion_labels):
            per_emotion_scores[label].append(sorted_predictions[index]["score"])
    return {label: np.max(scores) for label, scores in per_emotion_scores.items()}

In [15]:
for i in range(10):
    isbn.append(books["isbn13"][i])
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)
    max_scores = calculate_max_emotion_scores(predictions)
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

In [16]:
emotion_scores

{'anger': [np.float64(0.06413355469703674),
  np.float64(0.6126194000244141),
  np.float64(0.06413355469703674),
  np.float64(0.35148441791534424),
  np.float64(0.08141238987445831),
  np.float64(0.23222465813159943),
  np.float64(0.5381842255592346),
  np.float64(0.06413355469703674),
  np.float64(0.3006700873374939),
  np.float64(0.06413355469703674)],
 'disgust': [np.float64(0.27359139919281006),
  np.float64(0.3482847809791565),
  np.float64(0.10400658845901489),
  np.float64(0.1507224589586258),
  np.float64(0.18449527025222778),
  np.float64(0.7271749377250671),
  np.float64(0.155854731798172),
  np.float64(0.10400658845901489),
  np.float64(0.279481440782547),
  np.float64(0.17792704701423645)],
 'fear': [np.float64(0.9281681180000305),
  np.float64(0.9425276517868042),
  np.float64(0.9723208546638489),
  np.float64(0.36070606112480164),
  np.float64(0.09504339843988419),
  np.float64(0.05136274918913841),
  np.float64(0.7474274635314941),
  np.float64(0.40449756383895874),
  np.float64(0.9155240654945374),
  np.float64(0.05136274918913841)],
 'joy': [np.float64(0.9327982664108276),
  np.float64(0.7044221758842468),
  np.float64(0.7672382593154907),
  np.float64(0.2518813908100128),
  np.float64(0.040564365684986115),
  np.float64(0.043375786393880844),
  np.float64(0.8725655674934387),
  np.float64(0.040564365684986115),
  np.float64(0.040564365684986115),
  np.float64(0.040564365684986115)],
 'sadness': [np.float64(0.6462157964706421),
  np.float64(0.8879395127296448),
  np.float64(0.5494772791862488),
  np.float64(0.7326847910881042),
  np.float64(0.8843898177146912),
  np.float64(0.621392011642456),
  np.float64(0.71219402551651),
  np.float64(0.5494772791862488),
  np.float64(0.840289294719696),
  np.float64(0.8603721857070923)],
 'surprise': [np.float64(0.9671575427055359),
  np.float64(0.11169009655714035),
  np.float64(0.11169009655714035),
  np.float64(0.11169009655714035),
  np.float64(0.47588005661964417),
  np.float64(0.11169009655714035),
  np.float64(0.40800145268440247),
  np.float64(0.8202825784683228),
  np.float64(0.35446134209632874),
  np.float64(0.11169009655714035)],
 'neutral': [np.float64(0.729602038860321),
  np.float64(0.2525460422039032),
  np.float64(0.07876544445753098),
  np.float64(0.07876544445753098),
  np.float64(0.07876544445753098),
  np.float64(0.2719033658504486),
  np.float64(0.07876544445753098),
  np.float64(0.23448672890663147),
  np.float64(0.13561387360095978),
  np.float64(0.07876544445753098)]}

In [17]:
from tqdm import tqdm

emotion_labels = ["anger", "disgust", "fear", "joy", "sadness", "surprise", "neutral"]
isbn = []
emotion_scores = {label: [] for label in emotion_labels}

for i in tqdm(range(len(books))):
    isbn.append(books["isbn13"][i])
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)
    max_scores = calculate_max_emotion_scores(predictions)
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

100%|██████████| 5789/5789 [35:03<00:00,  2.75it/s]

In [18]:
emotions_df = pd.DataFrame(emotion_scores)
emotions_df["isbn13"] = isbn

In [19]:
emotions_df

,anger,disgust,fear,joy,sadness,surprise,neutral,isbn13
0,0.064134,0.273591,0.928168,0.932798,0.646216,0.967158,0.729602,9780002005883
1,0.612619,0.348285,0.942528,0.704422,0.887940,0.111690,0.252546,9780002261982
2,0.064134,0.104007,0.972321,0.767238,0.549477,0.111690,0.078765,9780006178736
3,0.351484,0.150722,0.360706,0.251881,0.732685,0.111690,0.078765,9780006280897
4,0.081412,0.184495,0.095043,0.040564,0.884390,0.475880,0.078765,9780006280934
...,...,...,...,...,...,...,...,...
5784,0.064134,0.114383,0.051363,0.400263,0.883198,0.111690,0.227765,9788173031014
5785,0.009997,0.009929,0.339218,0.947779,0.375754,0.066685,0.057625,9788179921623
5786,0.064134,0.104007,0.459268,0.759456,0.951104,0.368111,0.078765,9788185300535
5787,0.064134,0.104007,0.051363,0.958549,0.915193,0.111690,0.078765,9789027712059
5788,0.064134,0.104007,0.051363,0.991484,0.549477,0.111690,0.078765,9789042003408

In [20]:
books = pd.merge(books, emotions_df, on = "isbn13")

In [21]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,...,title_and_subtitle,tagged_description,simple_categories,anger,disgust,fear,joy,sadness,surprise,neutral
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,...,Gilead,9780002005883 A NOVEL THAT READERS and critics...,Fiction,0.064134,0.273591,0.928168,0.932798,0.646216,0.967158,0.729602
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,...,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,Fiction,0.612619,0.348285,0.942528,0.704422,0.887940,0.111690,0.252546
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,...,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...",Fiction,0.064134,0.104007,0.972321,0.767238,0.549477,0.111690,0.078765
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,...,The Four Loves,9780006280897 Lewis' work on the nature of lov...,Nonfiction,0.351484,0.150722,0.360706,0.251881,0.732685,0.111690,0.078765
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,...,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le...",Nonfiction,0.081412,0.184495,0.095043,0.040564,0.884390,0.475880,0.078765
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5784,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,...,Journey to the East,9788173031014 This book tells the tale of a ma...,Nonfiction,0.064134,0.114383,0.051363,0.400263,0.883198,0.111690,0.227765
5785,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,...,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...,Fiction,0.009997,0.009929,0.339218,0.947779,0.375754,0.066685,0.057625
5786,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,...,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...,Nonfiction,0.064134,0.104007,0.459268,0.759456,0.951104,0.368111,0.078765
5787,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,...,The Berlin Phenomenology,9789027712059 Since the three volume edition o...,Nonfiction,0.064134,0.104007,0.051363,0.958549,0.915193,0.111690,0.078765
5788,9789042003408,9042003405,'I'm Telling You Stories',Helena Grice;Tim Woods,Literary Criticism,http://books.google.com/books/content?id=2lVyR...,This is a jubilant and rewarding collection of...,1998.0,3.70,136.0,...,'I'm Telling You Stories': Jeanette Winterson ...,9789042003408 This is a jubilant and rewarding...,Nonfiction,0.064134,0.104007,0.051363,0.991484,0.549477,0.111690,0.078765

In [22]:
books.to_csv("books_with_emotions.csv", index = False)